#!/bin/bash
clear
rm -rf load amsworker_* worker* infretis_data*.txt sim.log* error.txt* EXIT ams_inp/initial restart.toml infretis.restart
cp -r load_copy load

export NSCM=1 # cores used
export OMP_NUM_THREADS=2 # parallelization
export AMS_COPYSTATE_MOVES_RESULTS=1
mpirun -n 4 --mca pml ob1 --mca btl tcp,self,vader infretismpi -i infretis.toml 
#infretisrun -i infretis.toml
