[runner]
workers = 2
wmdrun = [
    1,
    1,
]

[simulation]
interfaces = [
    0.3,
    0.35,
    0.4,
    0.45,
    0.5,
]
steps = 100
seed = 0
load_dir = "load"
shooting_moves = [
    "sh",
    "sh",
    "wf",
    "wf",
    "wf",
]
ensemble_engines = [
    [
        "engine",
    ],
    [
        "engine",
    ],
    [
        "engine",
    ],
    [
        "engine",
    ],
    [
        "engine",
    ],
]

[simulation.tis_set]
maxlength = 20000
aimless = true
allowmaxlength = false
zero_momentum = true
temperature = 300
quantis = false
accept_all = false

[engine]
class = "ams"
engine = "ams"
timestep = 0.001
input_path = "ams_inp"
subcycles = 5

[orderparameter]
class = "Distance"
index = [
    0,
    3,
]
periodic = false

[output]
backup = "backup"
data_dir = "./"
order-file = 1
energy-file = 1
trajectory-file = -1
screen = 1
pattern = false
delete_old = true
data_file = "./infretis_data.txt"

[current]
traj_num = 8
cstep = 2
active = [
    5,
    6,
    2,
    7,
    4,
]
locked = [
    [
        [
            2,
        ],
        [
            "2",
        ],
    ],
]
size = 5

[current.frac]
2 = [
    "0.0",
    "0.0",
    "1.0",
    "0.0",
    "0.0",
    "0.0",
]
4 = [
    "0.0",
    "0.0",
    "0.0",
    "0.0",
    "2.0",
    "0.0",
]
5 = [
    "2.0",
    "0.0",
    "0.0",
    "0.0",
    "0.0",
    "0.0",
]
6 = [
    "0.0",
    "2.0",
    "0.0",
    "0.0",
    "0.0",
    "0.0",
]
7 = [
    "0.0",
    "0.0",
    "0.0",
    "1.0",
    "0.0",
    "0.0",
]

[current.rng_state]
bit_generator = "PCG64"
has_uint32 = 0
uinteger = 0

[current.rng_state.state]
state = 136626137344985782772388288880891475984
inc = 87136372517582989555478159403783844777
