#!/bin/bash
#SBATCH --partition=phys.edu.q           # Partition name
#SBATCH --job-name=AMS.TEST              # Job name
#SBATCH --nodes=1                        # Number of nodes
#SBATCH --ntasks-per-node=32             # Number of processes per node
#$#$#$#$#$#$##SBATCH --nodelist=phys-computeJ002      # Specific node
#SBATCH --time=2400:00:00                # Time limit hrs:min:sec
#SBATCH --error=slurm-%j.err             # SLURM error
#SBATCH --output=slurm-%j.out            # SLURM output
mamba init
mamba activate molmod
. $HOME/opt/ams/ams2023.205.r118896/amsbashrc.sh
# $AMSBIN/autolicense nogui -u u21543 -p 8M5NEH3y -m k.wilke@tue.nl
# Run an infRETIS calculations
chmod +x runner 
./runner

