#!/bin/bash
#SBATCH --partition=XXX           # Partition name
#SBATCH --nodelist=XXX
#SBATCH --job-name=XXX              # Job name
#SBATCH --nodes=1                        # Number of nodes
#SBATCH --ntasks-per-node=16             # Number of processes per node
#SBATCH --time=2400:00:00                # Time limit hrs:min:sec
#SBATCH --error=slurm-%j.err             # SLURM error
#SBATCH --output=slurm-%j.out            # SLURM output
mamba init
mamba activate molmod
# Run an infRETIS calculations
chmod +x runner 
./runner

